name: "changed-lines-number-action"
description: "Add the number of changed lines to the PR body, considering `.gitattributes`."
author: "aki77"
branding:
  icon: eye
  color: blue
inputs:
  token:
    description: "Github token"
    required: true
  hideLink:
    description: "Hide the link"
    default: "false"
    required: false
runs:
  using: "node20"
  main: "dist/index.js"
